name       : python-pytest
version    : 3.0.3
release    : 1
source     :
    - https://pypi.python.org/packages/a0/2f/076c816e2402c4911ccee4b93ba0475145b7cffd0320ca8efa0add7c469c/pytest-3.0.3.tar.gz : f213500a356800a483e8a146ff971ae14a8df3f2c0ae4145181aad96996abee7
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex fucntional testing for applications and libraries.
builddeps  :
    - python-setuptools
    - pkgconfig(python3)
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
