name       : python-pytest
version    : 6.2.5
release    : 19
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest/pytest-6.2.5.tar.gz : 131b36680866a76e6781d13f101efb86cf674ebb9762eb70d3082b6f29889e89
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - lsof
    - py
    - pygments # check
    - python-argcomplete # check
    - python-atomicwrites
    - python-hypothesis # check
    - python-iniconfig
    - python-jinja # check
    - python-mock # check
    - python-nose # check
    - python-setuptools-scm
    - python-packaging
    - python-pluggy
    - python-toml
    - python-wcwidth
    - python-xmlschema # check
rundeps    :
    - py
    - python-atomicwrites
    - python-attrs
    - python-iniconfig
    - python-packaging
    - python-pluggy
    - python-six
    - python-toml
    - python-wcwidth
build      : |
    %python3_setup
install    : |
    %python3_install
    # avoid conflict with python2-pytest
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
check      : |
    %python3_test $installdir/usr/bin/py.test3 -k 'not test_cache_failure_warns'
