name       : python-pytest
version    : 4.6.11
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest/pytest-4.6.11.tar.gz : 50fa82392f2120cc3ec2ca0a75ee615be4c479e66669789771f1758332be4353
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - lsof
    - py
    - python-atomicwrites
    - python-funcsigs
    - python-hypothesis
    - python-jinja
    - python-mock
    - python-more-itertools
    - python-nose
    - python-setuptools
    - python-setuptools-scm
    - python-pathlib2
    - python-pluggy
    - python-requests
    - python-wcwidth
rundeps    :
    - py
    - python-atomicwrites
    - python-attrs
    - python-funcsigs
    - python-more-itertools
    - python-pathlib2
    - python-pluggy
    - python-setuptools
    - python-six
    - python-wcwidth
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
check      : |
    #python_test $installdir/usr/bin/py.test -k 'not test_cache_failure_warns'
    %python3_test $installdir/usr/bin/py.test3 -k 'not test_cache_failure_warns'
