name       : python-pytest
version    : 3.4.0
release    : 6
source     :
    - https://pypi.python.org/packages/a8/84/25b93a15997be680fc8ce1a7b9315b03650ced546908e5008c0912b1c2e1/pytest-3.4.0.tar.gz : 6074ea3b9c999bd6d0df5fa9d12dd95ccd23550df2a582f5f5b848331d2e82ca
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - py
    - python-attrs
    - python-funcsigs
    - python-pluggy
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
