name       : python-pytest
version    : 3.9.1
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest/pytest-3.9.1.tar.gz : 8c827e7d4816dfe13e9329c8226aef8e6e75d65b939bc74fda894143b6d1df59
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - lsof
    - py
    - python-atomicwrites
    - python-funcsigs
    - python-hypothesis
    - python-jinja
    - python-mock
    - python-more-itertools
    - python-nose
    - python-setuptools
    - python-setuptools-scm
    - python-pathlib2
    - python-pluggy
    - python-requests
rundeps    :
    - py
    - python-atomicwrites
    - python-attrs
    - python-funcsigs
    - python-more-itertools
    - python-pathlib2
    - python-pluggy
    - python-setuptools
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python_test $installdir/usr/bin/py.test -k 'not test_cache_failure_warns'
    %python3_test $installdir/usr/bin/py.test3 -k 'not test_cache_failure_warns'
