name       : python-pytest
version    : 7.1.3
release    : 22
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest/pytest-7.1.3.tar.gz : 4f365fec2dff9c1162f834d9f18af1ba13062db0c708bf7b946f8a5c76180c39
homepage   : https://pytest.org/
license    : MIT
component  : programming.python
summary    : Simple powerful testing with Python
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - lsof
    - numpy
    - py
    - pygments           # check
    - python-argcomplete # check
    - python-decorator   # check
    - python-hypothesis  # check
    - python-iniconfig
    - python-jinja       # check
    - python-mock        # check
    - python-nose        # check
    - python-packaging
    - python-pluggy
    - python-setuptools-scm
    - python-twisted     # check
    - python-xmlschema   # check
rundeps    :
    - py
    - python-attrs
    - python-iniconfig
    - python-packaging
    - python-pluggy
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
    # avoid conflict with python2-pytest
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
check      : |
    %python3_test $installdir/usr/bin/py.test3 -v
