name       : python-pytest
version    : 7.2.0
release    : 23
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest/pytest-7.2.0.tar.gz : c4014eb40e10f11f355ad4e3c2fb2c6c6d1919c73f3b5a433de4708202cade59
homepage   : https://pytest.org/
license    : MIT
component  : programming.python
summary    : Simple powerful testing with Python
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - lsof
    - numpy
    - py
    - pygments              # check
    - python-argcomplete    # check
    - python-decorator      # check
    - python-exceptiongroup # check
    - python-hypothesis     # check
    - python-iniconfig
    - python-jinja          # check
    - python-mock           # check
    - python-nose           # check
    - python-packaging
    - python-pluggy
    - python-setuptools-scm
    - python-twisted        # check
    - python-xmlschema      # check
rundeps    :
    - py
    - python-attrs
    - python-exceptiongroup
    - python-iniconfig
    - python-packaging
    - python-pluggy
    - python-tomli
setup      : |
    # https://github.com/pytest-dev/pytest/issues/10473
    %patch -p1 < $pkgfiles/Fix-test_raising_repr-test.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    # avoid conflict with python2-pytest
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
check      : |
    %python3_test $installdir/usr/bin/pytest3 -v
