name       : python-pytest
version    : 7.4.0
release    : 24
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest/pytest-7.4.0.tar.gz : b4bf8c45bd59934ed84001ad51e11b4ee40d40a1229d2c79f9c592b0a3f6bd8a
homepage   : https://pytest.org/
license    : MIT
component  : programming.python
summary    : Simple powerful testing with Python
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - lsof
    - numpy
    - py
    - pygments              # check
    - python-argcomplete    # check
    - python-decorator      # check
    - python-exceptiongroup # check
    - python-hypothesis     # check
    - python-iniconfig
    - python-jinja          # check
    - python-mock           # check
    - python-nose           # check
    - python-packaging
    - python-pluggy
    - python-setuptools-scm
    - python-twisted        # check
    - python-xmlschema      # check
rundeps    :
    - py
    - python-attrs
    - python-exceptiongroup
    - python-iniconfig
    - python-packaging
    - python-pluggy
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install

    # Symlinking pytest3 and py.test3 to prevent check failures
    pushd $installdir/usr/bin
    ln -sv pytest pytest3
    ln -sv py.test py.test3
    popd
check      : |
    %python3_test $installdir/usr/bin/pytest -v
