name       : python-pytest
version    : 3.2.2
release    : 2
source     :
    - https://pypi.python.org/packages/63/4a/db317d848325ba77e4ed498860b40ab53a8b49f1ae13612bc8aee75634f0/pytest-3.2.2.tar.gz : f46e49e0340a532764991c498244a60e3a37d7424a532b3ff1a6a7653f1a403a
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex fucntional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - py
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
