name       : python-pytest
version    : 3.2.5
release    : 3
source     :
    - https://pypi.python.org/packages/1f/f8/8cd74c16952163ce0db0bd95fdd8810cbf093c08be00e6e665ebf0dc3138/pytest-3.2.5.tar.gz : 6d5bd4f7113b444c55a3bbb5c738a3dd80d43563d063fc42dcb0aaefbdd78b81
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex fucntional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - py
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
