name       : python-pytest
version    : 3.3.1
release    : 4
source     :
    - https://pypi.python.org/packages/fb/ee/ceb80b45e768e67ee848dfd4fc407a4ccfc6d93c904c49fad1e5495a079f/pytest-3.3.1.tar.gz : cf8436dc59d8695346fcd3ab296de46425ecab00d64096cebe79fb51ecb2eb93
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex fucntional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - py
    - python-attrs
    - python-funcsigs
    - python-pluggy
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
