name       : python-pytest
version    : 3.4.1
release    : 8
source     :
    - https://pypi.python.org/packages/84/11/a6fe751118861b4d6587e07633f2e055733fc3678f7e5d7ae30303d90b7e/pytest-3.4.1.tar.gz : 9ddcb879c8cc859d2540204b5399011f842e5e8823674bf429f70ada281b3cc6
license    : MIT
component  : programming.python
summary    : python testing framework
description: |
    The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - py
    - python-attrs
    - python-funcsigs
    - python-pluggy
    - python-setuptools
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
